fivetran_api_key = "YOUR FIVETRAN API KEY"
fivetran_api_secret = "YOUR FIVETRAN API SECRET"
fivetran_group_id = "YOUR FIVETRAN DESTINATION GROUP ID"
stripe_key = "YOUR STRIPE KEY"
stripe_connector_name = "stripe_example_prod"
